version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SESSION_SECRET=your-secure-session-secret
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/shahbaaz_auditorium
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=shahbaaz_auditorium
      - PGHOST=postgres
      - PGPORT=5432
    restart: unless-stopped
    volumes:
      - ./scripts:/app/scripts
    entrypoint: ["/bin/sh", "-c", "mkdir -p /tmp/scripts /tmp/scripts/migrations && cp -r /app/scripts/* /tmp/scripts/ && chmod +x /tmp/scripts/*.sh /tmp/scripts/migrations/*.sh && ls -la /tmp/scripts && cd /app && if [ -f /tmp/scripts/init-db.sh ]; then /tmp/scripts/init-db.sh; fi && if [ -f /tmp/scripts/migrate-db.sh ]; then /tmp/scripts/migrate-db.sh; fi && npm start"]

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shahbaaz_auditorium
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backups:/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shahbaaz_auditorium"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data: