version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SESSION_SECRET=your-secure-session-secret
      - SQLITE_FILE=/app/data/shahbaaz.db
    restart: unless-stopped
    volumes:
      - ./scripts:/app/scripts
      - sqlite-data:/app/data
      - ./backups:/app/backups
    entrypoint: ["/bin/sh", "-c", "cd /app && npm install && mkdir -p /tmp/scripts && cp -r /app/scripts/* /tmp/scripts/ && chmod +x /tmp/scripts/*.sh || true && if [ -f /app/scripts/init-db.js ]; then node /app/scripts/init-db.js || exit 1; fi && if [ -f /app/scripts/migrate-sqlite.ts ]; then npx tsx /app/scripts/migrate-sqlite.ts || true; fi && npm start"]

volumes:
  sqlite-data: