version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:5000"  # Map to standard HTTP port
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SESSION_SECRET=${SESSION_SECRET}
      - SQLITE_FILE=/app/data/shahbaaz.db
    restart: always
    volumes:
      - ./scripts:/app/scripts
      - sqlite-data:/app/data
      - ./backups:/app/backups
    entrypoint: ["/bin/sh", "-c", "mkdir -p /tmp/scripts && cp -r /app/scripts/* /tmp/scripts/ && chmod +x /tmp/scripts/*.sh || true && cd /app && if [ -f /tmp/scripts/init-db.js ]; then node /tmp/scripts/init-db.js || exit 1; fi && if [ -f /tmp/scripts/migrate-sqlite.ts ]; then npx tsx /tmp/scripts/migrate-sqlite.ts || true; fi && node server/index.js"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - app
    restart: always

volumes:
  sqlite-data: